### ISSUE TITLE
Minifying '0s' to '0' in Firefox in transition-delay

### ISSUE THREAD

**Issue by elidare** [css/csso#226]
Follow-up for #82 and #100.

-moz-transtion-delay: 0s;
transition-delay: 0s;

shouldn't be minified, as for transition-duration, too.

**Comment by Djules** [comment]
+1 for transition-duration on Chrome, it doesn't like the value without its unit.

**Comment by Strauch-Yaron** [comment]
Same goes for mixed statements in Chrome:

-webkit-transition: visibility 0s linear 1s;

shouldn't be minified to 0 as well

**Comment by dahart** [comment]
I bumped into this with the 'animation' property on Chrome.

Two observations -

- With multiple prefixed versions of the tag, the last one survives, but the rest don't.
Example, unminified:
#id {
  -webkit-animation : rotate 10s linear 0s infinite;
  -ms-animation : rotate 10s linear 0s infinite;
  animation : rotate 10s linear 0s infinite;
}
And minified:
#id{-webkit-animation:rotate 10s linear 0 infinite;-ms-animation:rotate 10s linear 0 infinite;animation:rotate 10s linear 0s infinite}

- A workaround is to use 0.01s, or something sufficiently small enough.

**Comment by lsirivong** [comment]
I encountered this recently as well. The crux of this issue as that [non-length dimensions are required to have units according to the spec](http://www.w3.org/TR/css-values/#other-units):

> A dimension is a number immediately followed by a unit identifier.

Lengths are explicitly allowed to omit the unit for zero values:

> Lengths refer to distance measurements and are denoted by `<length>` in the property definitions. A length is a dimension. However, **for zero lengths the unit identifier is optional** (i.e. can be syntactically represented as the `<number>` ‘0’).

Here's a [list of dimensions that are not `<length>`s](http://www.w3.org/TR/css-values/#other-units), and always require units:

* Angles
  * `deg`
  * `grad`
  * `rad`
  * `turn`
* Times
  * `s`
  * `ms`
* Frequencies
  * `Hz`
  * `kHz`
* Resolutions
  * `dpi`
  * `dpcm`
  * `dppx`

Hope this helps!

**Comment by lahmatiy** [comment]
Fixed in 1.3.12

**Comment by amiga-500** [comment]
Curious...although this was fixed a while back i am wondering if modern browsers still have this issue of unitless zeros.   From my tests it seems all the browsers now accept 0 without a unit.  Love to get anyones thoughts.

**Comment by henrykuijpers** [comment]
@amiga-500 , unfortunately the newest Chrome (on today's date) does not. It still shows invalid property value: 
![image](https://user-images.githubusercontent.com/6546957/92727329-3a1b2b80-f36f-11ea-92ec-a205ff717d8a.png)
